name: Docker Image CI 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:

  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "nikita21vp1" --password-stdin
        docker build . --file Dockerfile --tag nikita21vp1/app5:latest
        docker push nikita21vp1/app5:latest

